
package com.jwsur2.ch4.clientasync;

import java.util.List;
import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "RandService", targetNamespace = "http://random.ch4.jwsur2.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface RandService {


    /**
     * 
     * @return
     *     returns javax.xml.ws.Response<com.jwsur2.ch4.clientasync.Next1Response>
     */
    @WebMethod(operationName = "next1")
    @RequestWrapper(localName = "next1", targetNamespace = "http://random.ch4.jwsur2.com/", className = "com.jwsur2.ch4.clientasync.Next1")
    @ResponseWrapper(localName = "next1Response", targetNamespace = "http://random.ch4.jwsur2.com/", className = "com.jwsur2.ch4.clientasync.Next1Response")
    public Response<Next1Response> next1Async();

    /**
     * 
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "next1")
    @RequestWrapper(localName = "next1", targetNamespace = "http://random.ch4.jwsur2.com/", className = "com.jwsur2.ch4.clientasync.Next1")
    @ResponseWrapper(localName = "next1Response", targetNamespace = "http://random.ch4.jwsur2.com/", className = "com.jwsur2.ch4.clientasync.Next1Response")
    public Future<?> next1Async(
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<Next1Response> asyncHandler);

    /**
     * 
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "next1", targetNamespace = "http://random.ch4.jwsur2.com/", className = "com.jwsur2.ch4.clientasync.Next1")
    @ResponseWrapper(localName = "next1Response", targetNamespace = "http://random.ch4.jwsur2.com/", className = "com.jwsur2.ch4.clientasync.Next1Response")
    @Action(input = "http://random.ch4.jwsur2.com/RandService/next1Request", output = "http://random.ch4.jwsur2.com/RandService/next1Response")
    public int next1();

    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.jwsur2.ch4.clientasync.NextNResponse>
     */
    @WebMethod(operationName = "nextN")
    @RequestWrapper(localName = "nextN", targetNamespace = "http://random.ch4.jwsur2.com/", className = "com.jwsur2.ch4.clientasync.NextN")
    @ResponseWrapper(localName = "nextNResponse", targetNamespace = "http://random.ch4.jwsur2.com/", className = "com.jwsur2.ch4.clientasync.NextNResponse")
    public Response<NextNResponse> nextNAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "nextN")
    @RequestWrapper(localName = "nextN", targetNamespace = "http://random.ch4.jwsur2.com/", className = "com.jwsur2.ch4.clientasync.NextN")
    @ResponseWrapper(localName = "nextNResponse", targetNamespace = "http://random.ch4.jwsur2.com/", className = "com.jwsur2.ch4.clientasync.NextNResponse")
    public Future<?> nextNAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<NextNResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<java.lang.Integer>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "nextN", targetNamespace = "http://random.ch4.jwsur2.com/", className = "com.jwsur2.ch4.clientasync.NextN")
    @ResponseWrapper(localName = "nextNResponse", targetNamespace = "http://random.ch4.jwsur2.com/", className = "com.jwsur2.ch4.clientasync.NextNResponse")
    @Action(input = "http://random.ch4.jwsur2.com/RandService/nextNRequest", output = "http://random.ch4.jwsur2.com/RandService/nextNResponse")
    public List<Integer> nextN(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
